### ISSUE TITLE
The player name doesn't show up over head only %playername% (message).

### ISSUE THREAD

**Issue by deleniti** [TheDiVaZo/MessageOverHead#13]
I have no idea why it doesn't work properly. I have both dependencies installed Protocolib and placeholder API on paper 1.18.2.

**Comment by TheDiVaZo** [comment]
Please contact me on Discord and describe your issue if the following steps don't work:
Start the server with PAPI and ProtocolLib installed and my plugin.
Write the command /papi ecloud download Player
Restart the server or PAPI
%player_name% - placeholder name of player
My discrod: TheDiVaZo#3794
