### ISSUE TITLE
Request to add a gradient color as well as a color 

### ISSUE THREAD

**Issue by TalentsDX** [TheDiVaZo/MessageOverHead#14]
Please add a gradient color and color color code, because the monochrome bubble message in the game seems a bit monotonous 。(This message is the result of Google Translate)

**Comment by TheDiVaZo** [comment]
I will add this in update 1.19

**Comment by TheDiVaZo** [comment]
Gradient has not been added yet you can use the site https://rgb.birdflop.com/
I will close this question when I add a gradient

**Comment by TheDiVaZo** [comment]
Added
