### ISSUE TITLE
Message does not display my name correct for me.

### ISSUE THREAD

**Issue by Aurelius-Ari** [TheDiVaZo/MessageOverHead#16]
The Message displays my name as the placeholder "%player_name%" not as "Aurelius_Ari". Is that just a problem for myself? Wanna have the server up as a surprise and want stuff to fully work so, sorry if I have to this here :D Dunno if it is an issue or not ^^

**Comment by Aurelius-Ari** [comment]
Also I cannot see the message for other players, nor can other see the message over my head. Just tested that.

**Comment by TheDiVaZo** [comment]
1. Download PAPI (Placeholder API). Write /papi ecloud download Player and see https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player
2. 
Did you remember to give the players permission to view messages?
default permissions:
moh.see
moh.send

**Comment by TheDiVaZo** [comment]
thedivazo#3794 - My Discord
