### ISSUE TITLE
Feature request for not showing private messages

### ISSUE THREAD

**Issue by Niko302** [TheDiVaZo/MessageOverHead#17]
When you write /msg [player] you enter private message mode and then you write messages to each other without this command.
When players are in private message mode we don't want the chat to be shown above a player.

plugin using this feature:  https://builtbybit.com/resources/chatcontrol-red-format-filter-your-chat-1-chat-plugin-1-2-5-1-19-2-10-off.18217/

**Comment by TheDiVaZo** [comment]
Added
