### ISSUE TITLE
Whenever a message despawns, it prints "[MessageOverHead] DELETE" to console

### ISSUE THREAD

**Issue by notjoshmiles** [TheDiVaZo/MessageOverHead#19]
![image](https://user-images.githubusercontent.com/19347018/185913259-ab476507-04f8-47c9-8fb4-a4d427cc236a.png)
I'm assuming this isn't intentional

**Comment by TheDiVaZo** [comment]
Yes, I forgot to remove the debug message. I will release a new version to fix this issue.
