### ISSUE TITLE
Particles appearing even when disabled via config

### ISSUE THREAD

**Issue by notjoshmiles** [TheDiVaZo/MessageOverHead#22]
![image](https://user-images.githubusercontent.com/19347018/186212678-cc3e50c6-9630-4b57-8a9d-35c65c59a24e.png)
![image](https://user-images.githubusercontent.com/19347018/186212752-ab8eb89f-1e80-47b6-9979-86896b88f000.png)
Latest Spigot build

**Comment by TheDiVaZo** [comment]
messages:
  particle:
    enable: false
    particleType: CLOUD # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    count: 4 #count of particle
    offsetX: 0.2 #the maximum random offset on the X axis
    offsetY: 0.2 #the maximum random offset on the X axis
    offsetZ: 0.2 #the maximum random offset on the Z axis

copy and paste

**Comment by notjoshmiles** [comment]
@TheDiVaZo that's the same as I currently have, no?
