### ISSUE TITLE
plugin dont work

### ISSUE THREAD

**Issue by Glitcher232** [TheDiVaZo/MessageOverHead#30]
Purpur 1.19.3 1894
When sending a message, it kicks from the server, give out such a strange error:
![2023-01-20_13-08-54](https://user-images.githubusercontent.com/78144786/213669774-5549bf6f-493c-4737-b730-55c3361b8505.png)

In the console writes the following:
![2023-01-20_13-10-10](https://user-images.githubusercontent.com/78144786/213671240-4e9a89cf-07a2-4699-a891-1fe8ec190a39.png)

as I said earlier the game version 1.19.3 on 1.18.2 the plugin works

**Comment by TheDiVaZo** [comment]
Hi, How your protocolLib version?

**Comment by Glitcher232** [comment]
Hello. 612, latest dev build

**Comment by TheDiVaZo** [comment]
Interesting errir, do you have a discord? Email me TheDiVaZo#3794

**Comment by Glitcher232** [comment]
yes, im Глитчер#6357

**Comment by jacobjake1** [comment]
Im getting the same error:

https://pastebin.com/raw/Ym5GnuUf

**Comment by TheDiVaZo** [comment]
plugin update. I fix this bug
https://www.spigotmc.org/resources/messageoverhead-pop-up-messages-above-your-head-1-13-1-19.100051/
