### ISSUE TITLE
Please don't check updates on the main thread

### ISSUE THREAD

**Issue by ahdg6** [TheDiVaZo/MessageOverHead#34]
When the server network status is not very good, plug-in check update tend to stop the server to start.

**Comment by TheDiVaZo** [comment]
Oh, okay. Fine. I will fix this in the next update.

**Comment by TheDiVaZo** [comment]
This problem has been fixed. Download new version https://www.spigotmc.org/resources/messageoverhead-pop-up-messages-above-your-head-1-12-1-19.100051/
